/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Conexion;
import Modelo.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.*;
import java.sql.*;
public class Login extends javax.swing.JFrame {

   int xMouse, yMouse;
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Informacion = new javax.swing.JPanel();
        NombreEmpresa = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        UsetTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        UsuarioPass = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        LoginBtn = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JPanel();
        ExitTxT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Informacion.setBackground(new java.awt.Color(143, 75, 40));

        NombreEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        NombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEmpresa.setText("La Guitarra");

        Nombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Sistema de inventario del almacen");

        Direccion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Direccion.setForeground(new java.awt.Color(255, 255, 255));
        Direccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direccion.setText("Calle 30 / Carrera 39-09");

        javax.swing.GroupLayout InformacionLayout = new javax.swing.GroupLayout(Informacion);
        Informacion.setLayout(InformacionLayout);
        InformacionLayout.setHorizontalGroup(
            InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacionLayout.createSequentialGroup()
                .addGroup(InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InformacionLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Nombre))
                    .addGroup(InformacionLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InformacionLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(NombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        InformacionLayout.setVerticalGroup(
            InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacionLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(NombreEmpresa)
                .addGap(18, 18, 18)
                .addComponent(Nombre)
                .addGap(28, 28, 28)
                .addComponent(Direccion)
                .addGap(241, 241, 241))
        );

        jPanel1.add(Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 510));

        Inicio.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Inicio.setText("INICIAR SESION");
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 220, -1));

        usuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        usuario.setText("USUARIO");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 70, -1));

        UsetTxt.setText("Ingrese su nombre de usuario");
        UsetTxt.setBorder(null);
        UsetTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsetTxtMousePressed(evt);
            }
        });
        UsetTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsetTxtActionPerformed(evt);
            }
        });
        jPanel1.add(UsetTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 300, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 250, -1));

        UsuarioPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        UsuarioPass.setText("CONTRASEÑA");
        jPanel1.add(UsuarioPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 110, -1));

        Password.setText("********");
        Password.setBorder(null);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordMousePressed(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 250, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 250, -1));

        LoginBtn.setBackground(new java.awt.Color(117, 80, 72));
        LoginBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Entrar");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 100, 50));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });

        ExitBtn.setBackground(new java.awt.Color(255, 255, 255));

        ExitTxT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ExitTxT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitTxT.setText("X");
        ExitTxT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitTxTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitTxTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitTxTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitBtnLayout = new javax.swing.GroupLayout(ExitBtn);
        ExitBtn.setLayout(ExitBtnLayout);
        ExitBtnLayout.setHorizontalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitTxT, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );
        ExitBtnLayout.setVerticalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitTxT, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 559, Short.MAX_VALUE)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsetTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsetTxtMousePressed
        UsetTxt.setText("");
        UsetTxt.setForeground(Color.black);
        Password.setText("********");
        Password.setForeground(Color.black);
    }//GEN-LAST:event_UsetTxtMousePressed

    private void UsetTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsetTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsetTxtActionPerformed

    private void PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMousePressed
        UsetTxt.setForeground(Color.black);
        Password.setText("");
        Password.setForeground(Color.black);
    }//GEN-LAST:event_PasswordMousePressed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // Obtener el nombre de usuario y la contraseña de los campos de texto
    String nombreUsuario = UsetTxt.getText();
    String contraseña = new String(Password.getPassword());

    // Verificar que los campos no estén vacíos
    if (nombreUsuario.isEmpty() || contraseña.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete ambos campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Crear una instancia de la clase Conexion y verificar las credenciales
    Conexion conexion = new Conexion();
    boolean loginExitoso = conexion.iniciarSesion(nombreUsuario, contraseña);

    // Mostrar un mensaje basado en el resultado del login
    if (loginExitoso) {
        JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
        
        // Abrir la interfaz principal
        Principal principal = new Principal();
        principal.setVisible(true);

        // Cerrar o esconder la ventana de login
        this.dispose(); // O usa this.setVisible(false) para ocultar la ventana sin cerrarla
    } else {
        JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void ExitTxTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTxTMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitTxTMouseClicked

    private void ExitTxTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTxTMouseEntered
        ExitBtn.setBackground(Color.red);
    }//GEN-LAST:event_ExitTxTMouseEntered

    private void ExitTxTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTxTMouseExited
        ExitBtn.setBackground(Color.white);
    }//GEN-LAST:event_ExitTxTMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Direccion;
    private javax.swing.JPanel ExitBtn;
    private javax.swing.JLabel ExitTxT;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Informacion;
    private javax.swing.JLabel Inicio;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreEmpresa;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField UsetTxt;
    private javax.swing.JLabel UsuarioPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
