/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Conexion;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

public class Registro extends javax.swing.JFrame {

    Conexion app = new Conexion();
   int xMouse, yMouse;
    public Registro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();
        DIreccion = new javax.swing.JLabel();
        UserPassword = new javax.swing.JPasswordField();
        UsetTxt = new javax.swing.JTextField();
        Inicio = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        UsuarioPass = new javax.swing.JLabel();
        usuario1 = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        NombreTxT = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Apellido = new javax.swing.JLabel();
        ApellidoTxT = new javax.swing.JTextField();
        RegistroBtn = new javax.swing.JPanel();
        RegistroTxT = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JPanel();
        ExitTxt = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(143, 75, 40));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("La Guitarra ");

        Info.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Info.setForeground(new java.awt.Color(255, 255, 255));
        Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Info.setText("Sistema de inventario del almacén");

        DIreccion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DIreccion.setForeground(new java.awt.Color(255, 255, 255));
        DIreccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DIreccion.setText("Calle 30 / Carrera 39-09");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(DIreccion, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Info)
                .addGap(18, 18, 18)
                .addComponent(DIreccion)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        Bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        UserPassword.setText("********");
        UserPassword.setBorder(null);
        UserPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserPasswordMousePressed(evt);
            }
        });
        UserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPasswordActionPerformed(evt);
            }
        });
        Bg.add(UserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        UsetTxt.setText("Ingrese su nombre de usuario");
        UsetTxt.setBorder(null);
        UsetTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsetTxtMousePressed(evt);
            }
        });
        UsetTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsetTxtActionPerformed(evt);
            }
        });
        Bg.add(UsetTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        Inicio.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inicio.setText("Sistema de Registro");
        Bg.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 220, -1));
        Bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 250, -1));
        Bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 250, -1));

        UsuarioPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        UsuarioPass.setText("CONTRASEÑA");
        Bg.add(UsuarioPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 110, -1));

        usuario1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        usuario1.setText("USUARIO");
        Bg.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 70, -1));

        NombreUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        NombreUsuario.setText("NOMBRE");
        Bg.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 80, 30));

        NombreTxT.setText("Ingrese su nombre ");
        NombreTxT.setBorder(null);
        NombreTxT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombreTxTMousePressed(evt);
            }
        });
        NombreTxT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxTActionPerformed(evt);
            }
        });
        Bg.add(NombreTxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 250, -1));
        Bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 250, -1));

        Apellido.setText("APELLIDO");
        Bg.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        ApellidoTxT.setText("Ingrese su Apellido");
        ApellidoTxT.setBorder(null);
        ApellidoTxT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ApellidoTxTMousePressed(evt);
            }
        });
        Bg.add(ApellidoTxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 240, -1));

        RegistroBtn.setBackground(new java.awt.Color(117, 80, 72));

        RegistroTxT.setForeground(new java.awt.Color(255, 255, 255));
        RegistroTxT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistroTxT.setText("REGISTRARSE");
        RegistroTxT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistroTxTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistroTxTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistroTxTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout RegistroBtnLayout = new javax.swing.GroupLayout(RegistroBtn);
        RegistroBtn.setLayout(RegistroBtnLayout);
        RegistroBtnLayout.setHorizontalGroup(
            RegistroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistroTxT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        RegistroBtnLayout.setVerticalGroup(
            RegistroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistroTxT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Bg.add(RegistroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, 30));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });

        ExitBtn.setBackground(new java.awt.Color(255, 255, 255));

        ExitTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ExitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitTxt.setText("X");
        ExitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitBtnLayout = new javax.swing.GroupLayout(ExitBtn);
        ExitBtn.setLayout(ExitBtnLayout);
        ExitBtnLayout.setHorizontalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        ExitBtnLayout.setVerticalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitBtnLayout.createSequentialGroup()
                .addComponent(ExitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 546, Short.MAX_VALUE)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Bg.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));
        Bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 250, -1));
        Bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 413, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void UsetTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsetTxtActionPerformed
       UsetTxt.setText("");
        UsetTxt.setForeground(Color.black);
        UserPassword.setText("********");
        UserPassword.setForeground(Color.black);
    }//GEN-LAST:event_UsetTxtActionPerformed

    private void NombreTxTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxTActionPerformed

    private void RegistroTxTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroTxTMouseEntered
        RegistroBtn.setBackground(new Color(143, 75,40));
    }//GEN-LAST:event_RegistroTxTMouseEntered

    private void RegistroTxTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroTxTMouseExited
        RegistroBtn.setBackground(new Color(117, 80,72));
    }//GEN-LAST:event_RegistroTxTMouseExited

    private void RegistroTxTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroTxTMousePressed

        String Usuario = UsetTxt.getText();
String Contraseña = new String(UserPassword.getPassword());
String nombre = NombreTxT.getText();
String Apellido = ApellidoTxT.getText();

// Verificar que todos los campos estén llenos
if (Usuario.isEmpty() || Contraseña.isEmpty() || nombre.isEmpty() || Apellido.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Rellenar todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
    return; 
}

// Crear el objeto Usuario
Usuario nuevoUsuario = new Usuario(Usuario, Contraseña, nombre, Apellido);

// Intentar registrar el usuario
boolean registrado = app.registrarUsuario(nuevoUsuario);

// Mostrar mensaje basado en el resultado del registro
if (registrado) {
    JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    
    // Cerrar la ventana de registro
    this.dispose();

    // Abrir la interfaz principal
    Principal principalInterfaz = new Principal();
    principalInterfaz.setVisible(true);

} else {
    // Verificar si el fallo se debe a que el usuario ya existe
    if (app.usuarioExiste(Usuario)) {
        JOptionPane.showMessageDialog(this, "El usuario ya está registrado", "Advertencia", JOptionPane.WARNING_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    }//GEN-LAST:event_RegistroTxTMousePressed

    private void ExitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitTxtMouseClicked

    private void ExitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTxtMouseEntered
        ExitBtn.setBackground(Color.red);
    }//GEN-LAST:event_ExitTxtMouseEntered

    private void ExitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTxtMouseExited
        ExitBtn.setBackground(Color.white);
    }//GEN-LAST:event_ExitTxtMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void UserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPasswordActionPerformed

    }//GEN-LAST:event_UserPasswordActionPerformed

    private void UserPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserPasswordMousePressed
        UsetTxt.setForeground(Color.black);
        UserPassword.setText("");
        UserPassword.setForeground(Color.black);    }//GEN-LAST:event_UserPasswordMousePressed

    private void UsetTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsetTxtMousePressed
        UsetTxt.setText("");
        UsetTxt.setForeground(Color.black);
        UserPassword.setText("********");
        UserPassword.setForeground(Color.black);
    }//GEN-LAST:event_UsetTxtMousePressed

    private void NombreTxTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxTMousePressed
        NombreTxT.setText("");
        NombreTxT.setForeground(Color.black);
        ApellidoTxT.setText("Ingrese su Apellido");
        ApellidoTxT.setForeground(Color.black);
    }//GEN-LAST:event_NombreTxTMousePressed

    private void ApellidoTxTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApellidoTxTMousePressed
        NombreTxT.setForeground(Color.black);
        ApellidoTxT.setText("");
        ApellidoTxT.setForeground(Color.black);        
    }//GEN-LAST:event_ApellidoTxTMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField ApellidoTxT;
    private javax.swing.JPanel Bg;
    private javax.swing.JLabel DIreccion;
    private javax.swing.JPanel ExitBtn;
    private javax.swing.JLabel ExitTxt;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel Inicio;
    private javax.swing.JTextField NombreTxT;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JPanel RegistroBtn;
    private javax.swing.JLabel RegistroTxT;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPasswordField UserPassword;
    private javax.swing.JTextField UsetTxt;
    private javax.swing.JLabel UsuarioPass;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel usuario1;
    // End of variables declaration//GEN-END:variables
}
